spring.application.name=websocketdemo
server.port=8345
spring.threads.virtual.enabled=true
SECRET_KEY_WS=NmE0MXUkIiMvVCVFJVRZQVNUUkRIRFNBSkhHREZZRFNBWUZEU1RSWURTQSVFJiUjJCQlKCk9KSkoamhkc2poZHNhaGgkJSUkNDY1Xzs6L3NhaGdkc1ciIyQhwrAmVFRHWSZfOmprb1tdcD/CocOxfcORw5FsSkhV
KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:29092
KAFKA_GROUP_ID=group_id
KAFKA_MESSAGE_CHAT_TOPIC=chat_messages_demo
